### PR TITLE
Comments, revisited

### LINKED ISSUE #348: Line order of comments and code is not preserved
**Describe the bug**

The line order of comments and code is not preserved after formatting.

* When using leading commas, comments can be "shifted" upwards to the preceding CTE/column.
* For short select statements, all comments are moved above the `select` keyword instead

**To Reproduce**

```sql
with table_a as (
    select
        /* Notice that this select statement can fit on a single line without comments */
        col1,
        col2, -- col2
        /* Special column */
        special_column,
    from {{ ref("table_a" )}}
)

/* Some interesting comments above a CTE with a leading comma */
, table_b as (
    select *
    from {{ ref("table_b") }}
)

select *
from table_a, table_b
```

**Expected behavior**

The columns in the `table_a` CTE should continue to stay on different lines to preserve the meaning of the comments. The comment above the `table_b` CTE should also stay above it, despite using a leading comma.

```sql
with
    table_a as (
        select 
            /* Notice that this select statement can fit on a single line without comments */
            col1,
            col2, -- col2 
            /* Special column */
            special_column
        from {{ ref("table_a") }}
    ),
    /* Some interesting comments above a CTE with a leading comma */
    table_b as (select * from {{ ref("table_b") }})

select *
from table_a, table_b
```

**Actual behavior**

Because the `select` statement in the `table_a` CTE can fit on a single line, all comments were pushed above the CTE (including in-line comments).

The comment above the `table_b` CTE was also pushed above the `table_a` CTE (presumably because of the leading comma).

```sql
with
    /* Notice that this select statement can fit on a single line without comments */
    -- col2
    /* Special column */
    /* Some interesting comments above a CTE with a leading comma */
    table_a as (select col1, col2, special_column, from {{ ref("table_a") }}),
    table_b as (select * from {{ ref("table_b") }})

select *
from table_a, table_b
```

**Additional context**
What is the output of `sqlfmt --version`?

```bash
❯ sqlfmt --version
sqlfmt, version 0.14.3
```

### PR DESCRIPTION
**Pull request by tconbeer**
This PR ended up totally rethinking and rewriting comment handling. It was spurred by #348, but ended up doing more.

For the purposes of stability, we no longer push long inline comments to be standalone comments. This also helps
preserve the meaning of the position of the inline comments (this isn't always important, but sometimes it is).

This means that sometimes lines can exceed the max desired line length (including the inline comment).

- feat: revisit comments, close #348
- chore: improve unit testing and docs
- fix: allow merging if lines end in trailing inline comment
- fix: allow merging ahead of inline comments'
- fix: allow merging of blank lines after inline comments
- fix: keep inline comments inline
- fix: strip whitespace when splitting comments onto multiple lines
- fix: merge through comments if directly after standalone operator
- chore: bump primer refs

### CODE REVIEW

File: tests/data/unformatted/200_base_model.sql [hunk 1]
```diff
@@ -1,42 +1,3 @@
-with source as (select * from {{ source('my_application', 'users') }}),
```
Comment (tconbeer) [inline tests/data/unformatted/200_base_model.sql:1]: Whoops. Need to restore this.

**Review by tconbeer — COMMENTED** [review]
Improve it
